@host=https://localhost:7067

POST {{host}}/auth/register
Content-Type: application/json

{
	"firstName":"Hassan",
	"lastName":"Mohamed",
	"email":"hassanmohamed_hm@hotmail.com",
	"password":"P@ssw0rd"
}

